### ISSUE TITLE
Change date format

### ISSUE THREAD

**Issue by hellocatfood** [n1ywb/jeffs-gnucash-utils#6]
Currently, this script renders invoices using the North Amerian way of writing dates i.e. Year-Day-Month. In the UK (where I'm based) we use Year-Month-Day. Is there a way to change this in the script?

**Comment by n1ywb** [comment]
At first glance I think the date formatting is happening inside gnucash. I looked in my gnucash preferences and I do see a date format setting with a euro option. Can you give that a shot and let us know how it goes?

**Comment by hellocatfood** [comment]
It seems I have to explicitly set the date format to UK (instead of Locale) to get this to work. Thanks for your help!

**Comment by n1ywb** [comment]
It wold be nice if gncash respected your locale settings; I suggest you
open a bug on their tracker.

Thanks for using my invoice module!

On Fri, Mar 6, 2015 at 6:28 AM, Antonio <notifications@github.com> wrote:

> It seems I have to explicitly set the date format to UK (instead of
> Locale) to get this to work. Thanks for your help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/n1ywb/jeffs-gnucash-utils/issues/6#issuecomment-77545290>
> .
>



-- 
73 de n1ywb
